const CREATED = 201;
const BAD_REQUEST = 400;
const  UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;

module.exports = {
  CREATED, BAD_REQUEST, NOT_FOUND, INTERNAL_SERVER_ERROR,
};
